# Generated by Django 3.0.5 on 2020-04-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.AlterModelTable(
            name='post',
            table='POST',
        ),
    ]
